# Generated by Django 5.2.7 on 2025-10-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_realisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='realisation',
            old_name='date_realisation',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='type_metier',
        ),
        migrations.AddField(
            model_name='realisation',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='metiers',
            field=models.ManyToManyField(related_name='artisans', to='artisans.metier'),
        ),
    ]
