# Generated by Django 5.2.7 on 2025-10-22 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0003_metier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='username',
            field=models.CharField(error_messages={'unique': 'Un utilisateur avec ce nom existe déjà.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message="Le nom d'utilisateur peut contenir des lettres, chiffres, espaces et @/./+/-/_", regex='^[\\w.@+\\-\\s]+$')]),
        ),
    ]
