# Generated by Django 5.2.7 on 2025-10-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0004_alter_artisan_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='artisan',
            managers=[
            ],
        ),
    ]
