# Generated by Django 5.2.7 on 2025-10-24 14:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0005_alter_artisan_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message="Le nom d'utilisateur peut contenir des lettres, chiffres, espaces et @/./+/-/_", regex='^[\\w.@+\\-\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur_nom', models.CharField(max_length=150)),
                ('texte', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='artisans.realisation')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='artisans.realisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('realisation', 'user', 'ip_address')},
            },
        ),
    ]
