# Generated by Django 5.2.7 on 2025-10-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0006_alter_artisan_username_alter_realisation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('realisation', 'user')},
        ),
    ]
