# Generated by Django 5.2.7 on 2025-10-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0007_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('realisation', 'user'), name='unique_like_per_user'),
        ),
    ]
