# Generated by Django 5.2.7 on 2025-10-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0008_like_unique_like_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like_per_user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('realisation', 'user'), name='unique_like_per_user'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('realisation', 'ip_address'), name='unique_like_per_ip'),
        ),
    ]
