# Generated by Django 5.2.5 on 2026-02-23 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0009_remove_like_unique_like_per_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='metier',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='realisation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='artisan',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message="Le nom d'utilisateur peut contenir des lettres, chiffres, espaces et @/./+/-/_.", regex='^[\\w.@+\\-\\s]+$')]),
        ),
    ]
